// Contract.kt
package com.example.inventory

import android.provider.BaseColumns

object Contract {
    // Define table contents
    object InventoryEntry : BaseColumns {
        const val TABLE_NAME = "inventory"
        const val COLUMN_NAME_NAME = "name"
        const val COLUMN_NAME_DOB = "dob"
        const val COLUMN_NAME_GENDER = "gender"
        const val COLUMN_NAME_AGE = "age"
        const val COLUMN_NAME_CITY = "city"
        const val COLUMN_NAME_STATE = "state"
        const val COLUMN_NAME_PIN = "pin"
        const val COLUMN_NAME_EDUCATION = "education"
        const val COLUMN_NAME_INFORMANT_NAME = "informantName"
        const val COLUMN_NAME_CONCERN1 = "concern1"
        const val COLUMN_NAME_CONCERN2 = "concern2"
        const val COLUMN_NAME_CONCERN3 = "concern3"
        const val COLUMN_NAME_MODE_OF_ONSET = "modeOfOnset"
        const val COLUMN_NAME_DURATION = "duration"
        const val COLUMN_NAME_SLEEP = "sleep"
        const val COLUMN_NAME_APPETITE = "appetite"
        const val COLUMN_NAME_NATURE_OF_TREATMENT = "natureOfTreatment"
        const val COLUMN_NAME_MEDICINE = "medicine"
        const val COLUMN_NAME_DURATION_OF_TREATMENT = "durationOfTreatment"
        const val COLUMN_NAME_RESPONSE = "response"
        const val COLUMN_NAME_FAMILY_HISTORY = "familyHistory"
        const val COLUMN_NAME_FAMILY_TYPE = "familyType"
        const val COLUMN_NAME_CONSANGUINITY = "consanguinity"
        const val COLUMN_NAME_PARENTAL_MARRIAGE = "parentalMarriage"
        const val COLUMN_NAME_RESIDENCE = "residence"
        const val COLUMN_NAME_FAMILY_SIZE = "familySize"
        const val COLUMN_NAME_FAMILY_INCOME = "familyIncome"
        const val COLUMN_NAME_HEALTH_DETAILS = "health_details"
        const val COLUMN_NAME_TRAUMA_DETAILS = "trauma_details"
        const val COLUMN_NAME_EDUCATION_QUALIFICATION = "education_qualification"
        const val COLUMN_NAME_REMARKS = "remarks"
        const val COLUMN_NAME_MENSTRUAL_HISTORY = "menstrual_history"
        const val COLUMN_NAME_HOMOSEXUALITY_RESPONSE = "homosexuality_response"
        const val COLUMN_NAME_LOVE_RELATIONSHIP_RESPONSE = "love_relationship_response"
        const val COLUMN_NAME_EMPLOYMENT_STATUS = "employment_status"
        const val COLUMN_NAME_JOB_STRESS = "job_stress"
        const val COLUMN_NAME_JOB_SATISFACTION = "job_satisfaction"
        const val COLUMN_NAME_PERFORMANCE_DESCRIPTION = "performance_description"
        const val COLUMN_NAME_OCCUPATION = "occupation"
        const val COLUMN_NAME_HABITS = "habits"
        const val COLUMN_NAME_HEALTH = "health"
        const val COLUMN_NAME_COMPATIBILITY = "compatibility"
        const val COLUMN_NAME_KIDS = "kids"
        const val COLUMN_NAME_SEXUAL_SATISFACTION = "sexual_satisfaction"
        const val COLUMN_NAME_SMOKING = "smoking"
        const val COLUMN_NAME_ALCOHOL = "alcohol"
        const val COLUMN_NAME_DRUGS = "drugs"
        const val COLUMN_NAME_PAAN_GUTKA = "paanGutka"
        const val COLUMN_NAME_OTHER_HABITS = "otherHabits"
        const val COLUMN_NAME_SPECIFIC_DETAILS = "specificDetails"
        const val COLUMN_NAME_LIKES_DISLIKES = "likesDislikes"
        const val COLUMN_NAME_INTERESTS = "interests"
        const val COLUMN_NAME_FOLLOW_UP_SESSION1 = "follow_up_session1"
        const val COLUMN_NAME_FOLLOW_UP_SESSION2 = "follow_up_session2"
        const val COLUMN_NAME_FOLLOW_UP_SESSION3 = "follow_up_session3"
        const val COLUMN_NAME_FOLLOW_UP_SESSION4 = "follow_up_session4"
    }
}
